language: node_js
node_js:
  - '10'

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn coverage

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
