apiVersion: v1
kind: Service
metadata:
  namespace: nielsen
  name: panel-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    component: panel-website
